import numpy as np
import rasterio
from scipy.optimize import curve_fit
from scipy.ndimage import binary_erosion
import geopandas as gpd
from shapely.geometry import box
import os
from tqdm import tqdm
from joblib import Parallel, delayed
import warnings
from scipy.optimize import OptimizeWarning
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Ignore harmonic fitting mathematical warnings
warnings.filterwarnings("ignore", category=OptimizeWarning)

# ================== 1. Parameters and Path Configuration ==================
# Note: Use relative paths for GitHub repository compatibility.

# [INPUT 1] Regional Remote Sensing Data
# Generated by: '02_GEE_Export_Composite_Image.js'
# Structure: 9-band composite (Bands 0-6: Monthly NDVI DOY 105-285; Band 7: NASADEM; Band 8: Mask)
tif_path = r"./data/2025.tif"

# [INPUT 2] Dynamic Reference Phenology Curves
# Generated by: '01_Generate_Reference_CSV.py' (based on GEE sample extraction)
reference_csv_path = r"./data/reference_phenology_ndvi.csv"

# [INPUT 3] Independent Validation Samples
# Used for point-based threshold optimization and accuracy assessment
validation_points_path = r"./data/validation_points.shp"
# Attribute table field name for true species labels
LABEL_FIELD = 'True_Speci'  

# [OUTPUT] High-confidence seed prompts for SAM2 segmentation
out_geojson_path = r"./results/sam_box_prompts_2025.geojson"

# Time axis (DOY) for TW-DTW distance calculation
doy_times = np.array([105, 135, 165, 195, 225, 255, 285])

# ================== 2. Reference Curves and Smoothing ==================
def load_reference_curves(csv_path):
    """Load raw 12-month NDVI reference series from the pre-processed CSV."""
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Reference CSV not found: {csv_path}. Please run step 01 first.")
    
    df_ref = pd.read_csv(csv_path)
    # Extract values as numpy arrays
    fr_data = df_ref['F_robusta'].values
    bf_data = df_ref['B_faberi'].values
    return fr_data, bf_data

# Load the dynamic reference data
fr_raw, bf_raw = load_reference_curves(reference_csv_path)

def harmonic_model(t, a0, a1, b1, a2, b2):
    return a0 + a1 * np.cos(t) + b1 * np.sin(t) + a2 * np.cos(2*t) + b2 * np.sin(2*t)

def fit_hants(raw_series):
    """Reconstruct continuous NDVI time series using harmonic analysis."""
    if len(raw_series) == 12:
        doys = np.array([15, 45, 75, 105, 135, 165, 195, 225, 255, 285, 315, 345])
    else:
        doys = np.array([105, 135, 165, 195, 225, 255, 285])

    t_valid = (doys - 1) / 365.0 * 2 * np.pi
    valid_idx = ~np.isnan(raw_series)

    if np.sum(valid_idx) < 5:
        return np.zeros(7)

    try:
        popt, _ = curve_fit(harmonic_model, t_valid[valid_idx], raw_series[valid_idx], maxfev=10000)
        t_target = (np.array([105, 135, 165, 195, 225, 255, 285]) - 1) / 365.0 * 2 * np.pi
        return harmonic_model(t_target, *popt)
    except:
        return np.zeros(7)

# ================== 3. TW-DTW Core Algorithm ==================
def tw_dtw_distance(s1, s2, t1, t2, alpha=0.1, beta=30, omega=0.1):
    """Calculate Time-Weighted Dynamic Time Warping distance."""
    n, m = len(s1), len(s2)
    dist_matrix = (s1[:, None] - s2[None, :]) ** 2
    time_diff = np.abs(t1[:, None] - t2[None, :])
    time_penalty = 1.0 / (1.0 + np.exp(-alpha * (time_diff - beta)))
    cost_matrix = dist_matrix + omega * time_penalty

    dp = np.full((n + 1, m + 1), np.inf)
    dp[0, 0] = 0
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            cost = cost_matrix[i - 1, j - 1]
            dp[i, j] = cost + min(dp[i - 1, j], dp[i, j - 1], dp[i - 1, j - 1])
    return np.sqrt(dp[n, m])

# ================== 4. Ecological Niche Weights ==================
def weight_fr(elevation):
    """Elevation suitability weight for Fargesia robusta."""
    if 1800 <= elevation <= 2600: return 1.0
    elif 1600 <= elevation < 1800: return 0.5 + 0.5 * (elevation - 1600) / 200.0
    elif 2600 < elevation <= 2800: return 1.0 - 0.5 * (elevation - 2600) / 200.0
    else: return 0.1

def weight_bf(elevation):
    """Elevation suitability weight for Bashania faberi."""
    if 2800 <= elevation <= 3600: return 1.0
    elif 2600 <= elevation < 2800: return 0.5 + 0.5 * (elevation - 2600) / 200.0
    elif 3600 < elevation <= 3800: return 1.0 - 0.5 * (elevation - 3600) / 200.0
    else: return 0.1

# ================== 5. Threshold Optimization & Mapping ==================
def extract_validation_features(tif_path, shp_path):
    print("Extracting sample point features and parsing attribute table...")
    gdf = gpd.read_file(shp_path)
    points = [(geom.x, geom.y) for geom in gdf.geometry]

    if LABEL_FIELD not in gdf.columns:
        raise ValueError(f"Cannot find field '{LABEL_FIELD}'. Please check the shapefile.")

    raw_labels = gdf[LABEL_FIELD].values 
    true_labels = []

    for val in raw_labels:
        if pd.isna(val): 
            true_labels.append(0)
            continue

        val_str = str(val).strip().upper()
        # Parse original labels (GGZ -> F. robusta, LJZ -> B. faberi)
        if val_str == 'GGZ': true_labels.append(1)
        elif val_str in ['LJZ', 'LZJ']: true_labels.append(2)
        else: true_labels.append(0)

    true_labels = np.array(true_labels)
    features = []

    with rasterio.open(tif_path) as src:
        for val, (x, y) in zip(src.sample(points), points):
            ndvi_seq = val[0:7].astype(float)
            dem = val[7]
            features.append((ndvi_seq, dem))

    print(f"Parsed {len(true_labels)} points. (F. robusta: {np.sum(true_labels==1)}, B. faberi: {np.sum(true_labels==2)}, Background: {np.sum(true_labels==0)})")
    return features, true_labels

def calculate_metrics(features, true_labels, t_fr, t_bf, ref_fr, ref_bf, times):
    tp = 0  
    fp = 0  
    fn = 0  

    for (ndvi, dem), true_label in zip(features, true_labels):
        ndvi[ndvi <= 0] = np.nan
        ndvi[ndvi > 1] = np.nan
        pixel_smoothed = fit_hants(ndvi)

        pred_label = 0
        if np.max(pixel_smoothed) > 0:
            d_fr = tw_dtw_distance(pixel_smoothed, ref_fr, times, times) / weight_fr(dem)
            d_bf = tw_dtw_distance(pixel_smoothed, ref_bf, times, times) / weight_bf(dem)

            if d_fr < d_bf and d_fr <= t_fr: pred_label = 1
            elif d_bf < d_fr and d_bf <= t_bf: pred_label = 2

        if pred_label != 0: 
            if pred_label == true_label: tp += 1
            else: fp += 1
        else:
            if true_label != 0: fn += 1

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0

    if (precision + recall) > 0:
        f05_score = (1 + 0.5**2) * (precision * recall) / ((0.5**2 * precision) + recall)
    else:
        f05_score = 0.0

    return precision, f05_score

def optimize_thresholds_and_plot(features, true_labels, ref_fr, ref_bf, times):
    print("Starting dual-threshold grid search...")

    fr_range = np.arange(0.15, 0.51, 0.01)
    bf_range = np.arange(0.15, 0.51, 0.01)

    results = []
    best_f05 = 0
    base_t_fr = 0.34
    base_t_bf = 0.31

    for tf in tqdm(fr_range, desc="Parameter space search"):
        for tb in bf_range:
            precision, f05 = calculate_metrics(features, true_labels, tf, tb, ref_fr, ref_bf, times)
            results.append({'T_FR': round(tf, 2), 'T_BF': round(tb, 2), 'Precision': precision, 'Score': f05})

            if f05 > best_f05:
                best_f05 = f05
                base_t_fr = round(tf, 2)
                base_t_bf = round(tb, 2)

    df_results = pd.DataFrame(results)

    # Origin export section
    out_dir = r"./results/accuracy_assessment"
    os.makedirs(out_dir, exist_ok=True)

    valid_min = df_results.loc[df_results['Precision'] > 0, 'Precision'].min()
    floor_value = round(valid_min - 0.01, 2) 
    df_results.loc[df_results['Precision'] < 0.1, 'Precision'] = floor_value

    matrix_df = df_results.pivot(index='T_BF', columns='T_FR', values='Precision')
    matrix_df = matrix_df.sort_index(ascending=True)
    heatmap_path = os.path.join(out_dir, "Origin_Heatmap_Matrix.csv")
    matrix_df.to_csv(heatmap_path)
    print(f"Heatmap matrix exported: {heatmap_path}")

    line_bf_fixed = df_results[df_results['T_BF'] == base_t_bf][['T_FR', 'Precision']]
    line_bf_fixed = line_bf_fixed.rename(columns={'T_FR': 'Threshold', 'Precision': f'Fixed_BF={base_t_bf}_Adjust_FR'})

    line_fr_fixed = df_results[df_results['T_FR'] == base_t_fr][['T_BF', 'Precision']]
    line_fr_fixed = line_fr_fixed.rename(columns={'T_BF': 'Threshold', 'Precision': f'Fixed_FR={base_t_fr}_Adjust_BF'})

    line_data = pd.merge(line_bf_fixed, line_fr_fixed, on='Threshold', how='outer').sort_values('Threshold')
    line_path = os.path.join(out_dir, "Origin_Line_Curves.csv")
    line_data.to_csv(line_path, index=False)
    print(f"Line chart data exported: {line_path}")

    final_t_fr = 0.28
    final_t_bf = 0.21

    try:
        final_precision_fr = line_bf_fixed.loc[line_bf_fixed['Threshold'] == final_t_fr, f'Fixed_BF={base_t_bf}_Adjust_FR'].values[0]
        final_precision_bf = line_fr_fixed.loc[line_fr_fixed['Threshold'] == final_t_bf, f'Fixed_FR={base_t_fr}_Adjust_BF'].values[0]
    except:
        final_precision_fr = 0
        final_precision_bf = 0

    print(f"Optimal thresholds locked -> F. robusta: {final_t_fr:.2f} (Precision {final_precision_fr*100:.2f}%), B. faberi: {final_t_bf:.2f} (Precision {final_precision_bf*100:.2f}%)")

    # Preview plot
    plt.figure(figsize=(16, 6))

    plt.subplot(1, 2, 1)
    matrix_df.columns = np.round(matrix_df.columns, 2)
    matrix_df.index = np.round(matrix_df.index, 2)

    sns.heatmap(matrix_df, cmap="YlGnBu", annot=False, 
                xticklabels=4, yticklabels=4,
                cbar_kws={'label': 'Precision'})
    plt.gca().invert_yaxis()
    plt.title("Precision Heatmap under Dual Thresholds")
    plt.xlabel("Rejection Threshold for F. robusta")
    plt.ylabel("Rejection Threshold for B. faberi")

    plt.subplot(1, 2, 2)
    plt.plot(line_data['Threshold'], line_data[f'Fixed_BF={base_t_bf}_Adjust_FR'], marker='o', linewidth=2, label=f'Fixed BF={base_t_bf:.2f}')
    plt.plot(line_data['Threshold'], line_data[f'Fixed_FR={base_t_fr}_Adjust_BF'], marker='s', linewidth=2, label=f'Fixed FR={base_t_fr:.2f}')
    plt.axvline(x=final_t_fr, color='#1f77b4', linestyle='--', alpha=0.5, label=f'FR Target ({final_t_fr:.2f})')
    plt.axvline(x=final_t_bf, color='#2ca02c', linestyle='--', alpha=0.5, label=f'BF Target ({final_t_bf:.2f})')
    plt.title("Seed Point Precision Response")
    plt.xlabel("Threshold")
    plt.ylabel("Precision")
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.6)

    plt.tight_layout()
    plot_path = os.path.join(out_dir, "Threshold_Optimization_Precision.png")
    plt.savefig(plot_path, dpi=300, bbox_inches='tight')

    return final_t_fr, final_t_bf

# ================== 6. Parallel Processing Function ==================
def process_single_row(ndvi_row, dem_row, mask_row, width, ref_fr, ref_bf, times, t_fr, t_bf):
    import warnings
    from scipy.optimize import OptimizeWarning
    warnings.filterwarnings("ignore", category=OptimizeWarning)

    row_class = np.zeros(width, dtype=np.uint8)
    for col in range(width):
        if mask_row[col] != 1: continue

        pixel_ndvi = ndvi_row[:, col].copy()
        pixel_ndvi[pixel_ndvi <= 0] = np.nan
        pixel_ndvi[pixel_ndvi > 1] = np.nan

        pixel_smoothed = fit_hants(pixel_ndvi)
        if np.max(pixel_smoothed) == 0: continue

        d_raw_fr = tw_dtw_distance(pixel_smoothed, ref_fr, times, times)
        d_raw_bf = tw_dtw_distance(pixel_smoothed, ref_bf, times, times)

        elev = dem_row[col]
        d_final_fr = d_raw_fr / weight_fr(elev)
        d_final_bf = d_raw_bf / weight_bf(elev)

        if d_final_fr < d_final_bf and d_final_fr <= t_fr: row_class[col] = 1
        elif d_final_bf < d_final_fr and d_final_bf <= t_bf: row_class[col] = 2

    return row_class

# ================== 7. Main Execution ==================
if __name__ == '__main__':
    fr_ref = fit_hants(fr_raw)
    bf_ref = fit_hants(bf_raw)

    # Phase 1: Optimization and Mapping
    features, true_labels = extract_validation_features(tif_path, validation_points_path)
    T_REJECT_FR, T_REJECT_BF = optimize_thresholds_and_plot(features, true_labels, fr_ref, bf_ref, doy_times)

    # Phase 2: Regional processing
    print("\nLoading regional remote sensing data...")
    with rasterio.open(tif_path) as src:
        img_data = src.read()
        transform = src.transform
        width = src.width
        height = src.height
        crs = src.crs

        ndvi_data = img_data[0:7, :, :]
        dem_data = img_data[7, :, :]
        mask_data = img_data[8, :, :]

    print(f"Launching parallel computation (T_REJECT_FR: {T_REJECT_FR:.2f}, T_REJECT_BF: {T_REJECT_BF:.2f})...")

    results = Parallel(n_jobs=-1)(
        delayed(process_single_row)(
            ndvi_data[:, row, :], dem_data[row, :], mask_data[row, :], 
            width, fr_ref, bf_ref, doy_times, T_REJECT_FR, T_REJECT_BF
        ) for row in tqdm(range(height), desc="Processing rows")
    )

    class_matrix = np.vstack(results)
    print("Computation complete. Executing morphological seed isolation...")

    fr_pure = binary_erosion(class_matrix == 1, structure=np.ones((3,3)))
    bf_pure = binary_erosion(class_matrix == 2, structure=np.ones((3,3)))

    boxes = []
    labels = []
    count_fr_final = 0
    count_bf_final = 0

    for row in tqdm(range(height), desc="Vectorization"):
        for col in range(width):
            bamboo_type = 0
            if fr_pure[row, col]: bamboo_type = 1
            elif bf_pure[row, col]: bamboo_type = 2

            if bamboo_type != 0:
                minx, maxy = transform * (col, row)
                maxx, miny = transform * (col + 1, row + 1)
                geom_box = box(minx, miny, maxx, maxy)
                boxes.append(geom_box)
                
                if bamboo_type == 1:
                    labels.append('F_robusta')
                    count_fr_final += 1
                else:
                    labels.append('B_faberi')
                    count_bf_final += 1

    if len(boxes) > 0:
        gdf = gpd.GeoDataFrame({'Species': labels}, geometry=boxes, crs=crs)
        os.makedirs(os.path.dirname(out_geojson_path), exist_ok=True)
        gdf.to_file(out_geojson_path, driver='GeoJSON')

        print(f"\nExtraction complete! {len(boxes)} seed boxes generated.")
        print(f"F. robusta: {count_fr_final} boxes, B. faberi: {count_bf_final} boxes.")
        print(f"Results saved to: {out_geojson_path}")
    else:
        print("\nWarning: No valid seed points extracted.")
